from __future__ import annotations


OBD_PARAMETERS: dict[str, dict[str, str]] = {
    "oil_temp_c": {"label": "ENGINE OIL", "unit": "deg C", "format": "temp", "min": 40, "max": 130, "category": "Temperaturen"},
    "dsg_temp_c": {"label": "DSG TEMP", "unit": "deg C", "format": "temp", "min": 20, "max": 130, "category": "Temperaturen"},
    "battery_voltage_v": {"label": "BATTERY", "unit": "V", "format": "voltage", "min": 10, "max": 16, "category": "Elektrisch"},
    "coolant_temp_c": {"label": "COOLANT", "unit": "deg C", "format": "temp", "min": 40, "max": 130, "category": "Temperaturen"},
    "intake_temp_c": {"label": "INTAKE AIR", "unit": "deg C", "format": "temp", "min": -20, "max": 80, "category": "Temperaturen"},
    "boost_bar": {"label": "BOOST", "unit": "bar", "format": "bar", "min": 0, "max": 2.5, "category": "Berekend"},
    "boost_estimated_bar": {"label": "BOOST EST", "unit": "bar", "format": "bar", "min": -1, "max": 2.5, "category": "Berekend"},
    "map_kpa": {"label": "MAP", "unit": "kPa", "format": "kpa", "min": 20, "max": 250, "category": "Lucht & druk"},
    "barometric_pressure_kpa": {"label": "BARO", "unit": "kPa", "format": "kpa", "min": 90, "max": 110, "category": "Lucht & druk"},
    "oil_pan_temp_c": {"label": "OIL PAN", "unit": "deg C", "format": "temp", "min": 40, "max": 130, "category": "Temperaturen"},
    "transmission_fluid_temp_c": {"label": "DSG OIL", "unit": "deg C", "format": "temp", "min": 20, "max": 130, "category": "Temperaturen"},
    "tcu_module_temp_c": {"label": "TCU", "unit": "deg C", "format": "temp", "min": 0, "max": 110, "category": "Temperaturen"},
    "absolute_intake_pressure_bar": {"label": "INTAKE ABS", "unit": "bar", "format": "bar", "min": 0, "max": 2.5, "category": "Lucht & druk"},
    "ambient_air_pressure_bar": {"label": "AMBIENT", "unit": "bar", "format": "bar", "min": 0.7, "max": 1.1, "category": "Lucht & druk"},
    "engine_oil_pressure_actual_bar": {"label": "OIL PRESSURE", "unit": "bar", "format": "bar", "min": 0, "max": 8, "category": "Experimental"},
    "engine_oil_pressure_setpoint_bar": {"label": "OIL PRESS SET", "unit": "bar", "format": "bar", "min": 0, "max": 8, "category": "Experimental"},
    "transmission_oil_pressure_actual_bar": {"label": "DSG PRESSURE", "unit": "bar", "format": "bar", "min": 0, "max": 30, "category": "Experimental"},
    "transmission_input_speed_rpm": {"label": "DSG INPUT", "unit": "rpm", "format": "rpm", "min": 0, "max": 8000, "category": "Transmissie"},
    "selector_lever_position_raw": {"label": "SELECTOR", "unit": "raw", "format": "raw", "min": 0, "max": 0, "category": "Transmissie"},
    "displayed_gear_raw": {"label": "GEAR RAW", "unit": "raw", "format": "raw", "min": 0, "max": 0, "category": "Transmissie"},
    "oil_level_available": {"label": "OIL LEVEL", "unit": "status", "format": "status", "min": 0, "max": 1, "category": "Motorolie"},
    "oil_level_status_raw": {"label": "OIL RAW", "unit": "raw", "format": "raw", "min": 0, "max": 0, "category": "Motorolie"},
    "oil_level_method_1_pct": {"label": "OIL LVL 1", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_method_2_pct": {"label": "OIL LEVEL", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_method_3_pct": {"label": "OIL LVL 3", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_max_relative_pct": {"label": "OIL MAX", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_min_relative_pct": {"label": "OIL MIN", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_current_pct": {"label": "OIL CURRENT", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motorolie"},
    "oil_level_warning_raw": {"label": "OIL WARN", "unit": "raw", "format": "raw", "min": 0, "max": 0, "category": "Motorolie"},
    "rpm": {"label": "RPM", "unit": "rpm", "format": "rpm", "min": 0, "max": 8000, "category": "Motor"},
    "speed_kmh": {"label": "SPEED", "unit": "km/h", "format": "speed", "min": 0, "max": 240, "category": "Rijden"},
    "throttle_pct": {"label": "THROTTLE", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motor"},
    "engine_load_pct": {"label": "LOAD", "unit": "%", "format": "percent", "min": 0, "max": 100, "category": "Motor"},
    "fuel_consumption_l_per_100km": {"label": "CONSUMPTION", "unit": "L/100km", "format": "decimal", "min": 0, "max": 30, "category": "Rijden"},
    "act_active": {"label": "ACT ACTIEF", "unit": "", "format": "status", "min": 0, "max": 1, "category": "Experimental"},
}


PROVIDER_PARAMETERS: dict[str, list[str]] = {
    "simulated": list(OBD_PARAMETERS.keys()),
    "hexv2": [
        "oil_temp_c",
        "dsg_temp_c",
        "battery_voltage_v",
        "coolant_temp_c",
        "intake_temp_c",
        "boost_bar",
        "map_kpa",
        "barometric_pressure_kpa",
        "rpm",
        "speed_kmh",
    ],
    "elm327": [
        "oil_temp_c",
        "dsg_temp_c",
        "battery_voltage_v",
        "coolant_temp_c",
        "intake_temp_c",
        "rpm",
        "speed_kmh",
        "throttle_pct",
        "engine_load_pct",
        "fuel_consumption_l_per_100km",
        "act_active",
        "map_kpa",
        "barometric_pressure_kpa",
        "boost_bar",
        "boost_estimated_bar",
        "oil_pan_temp_c",
        "transmission_fluid_temp_c",
        "tcu_module_temp_c",
        "absolute_intake_pressure_bar",
        "ambient_air_pressure_bar",
        "engine_oil_pressure_actual_bar",
        "engine_oil_pressure_setpoint_bar",
        "transmission_oil_pressure_actual_bar",
        "transmission_input_speed_rpm",
        "selector_lever_position_raw",
        "displayed_gear_raw",
        "oil_level_available",
        "oil_level_status_raw",
        "oil_level_method_1_pct",
        "oil_level_method_2_pct",
        "oil_level_method_3_pct",
        "oil_level_max_relative_pct",
        "oil_level_min_relative_pct",
    ],
}
